# Generated by Django 2.0.5 on 2018-05-28 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='choice',
            name='score1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='choice',
            name='score2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='score1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='score2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='team1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='team1', to='polls.Team'),
        ),
        migrations.AddField(
            model_name='question',
            name='team2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='team2', to='polls.Team'),
        ),
    ]
