# Generated by Django 2.0.5 on 2018-07-02 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_team_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='score1_final',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='score2_final',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
